# Azure DevOps pipeline for Checkov scan on Terraform files

trigger:
  branches:
    include:
    - main

stages:
- stage: CheckovScan
  displayName: Checkov Scan
  jobs:
  - job: checkov_scan
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self

    # Install Checkov
    - bash: pip3 install checkov
      displayName: 'Install checkov'

    # Verify Terraform files with Checkov
    - bash: checkov --directory $(System.DefaultWorkingDirectory) -o junitxml > $(System.DefaultWorkingDirectory)/Checkov-Report.xml
      displayName: 'Verify Terraform with Checkov'
      name: 'checkov_check'

    # Publish Checkov test results
    - task: PublishTestResults@2
      displayName: Publish Checkov Test Results
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/*Checkov-Report.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: false
        testRunTitle: Checkov Scan
        failTaskOnFailedTests: false
        publishRunAttachments: true
